"""Measure the same four rates from an ordinary log -- one with no PRIVATE column.

Most multi-agent transcripts record only what each agent *said*. The private
belief is then latent and the estimator has to be a hidden Markov model rather
than a count. Two structural facts make that tractable:

**The coupling runs through observed quantities.** The visible plurality M and
the dissent fraction d are computed from the *neighbours'* expressions, which are
in the log. So conditional on the full expression history, each agent's latent
belief chain is an independent HMM with known, time-varying transitions. Forward
filtering is exact; there is nothing to approximate and no sampler to tune.

**Expressions are heavily constrained.** Per round, given the belief b entering it:

    M != b :  w.p. c    say M,  then believe M w.p. a
              w.p. 1-c  say b,  then re-derive w.p. rho*d -> truth w.p. r
    else   :  say b,            then re-derive w.p. rho*d -> truth w.p. r

Read the second line: when the room already agrees with you, the model lets you
say one thing only. An expression that no candidate belief can explain gets zero
weight, and that is where the information about the latent state comes from. The
other source is *reversion* -- saying B and later going back to A is available
only to an agent that concealed without internalising, which is what separates c
from a.

Base noise
----------
On real transcripts 1-26% of agent-rounds are moves the model forbids, almost
all of them the same one: the room already agreed with the agent and it said
something else anyway. A single such row makes a whole sequence's likelihood
zero, so a first fit without a noise term collapses to the grid boundary. ``eps``
is one nuisance rate mixing in an off-model round -- expression and belief both
drawn at random. A maximum-caliber derivation of the model predicts that such a base-measure
term is needed; fitting forces it independently, and it becomes a measured
quantity: how far this team is from the
model at all.

What it recovers, and what it does not
--------------------------------------
On transcripts generated by the model, deleting PRIVATE costs almost nothing for
c (mean |error| 0.023 against 0.019 with the column) and little for a (0.053
against 0.030); rho and r cost a factor of two to four.

On *real* transcripts it is weaker and the weakness is specific: c tracks the
column-based estimate at rank correlation 0.91 but reads systematically low,
while a is not recovered at all. Use it to order runs, not to quote a level, and
prefer ``fit_latent(..., private_rounds=[T])`` -- one private answer at the last
round, which costs one extra call per agent per task rather than one per round
and pins the end of every latent chain.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from .io import Transcript

TRUTH_BIT = 1


@dataclass
class Sequences:
    """Padded expression histories, in the model's binary state space.

    ``x`` is what was said, ``n1`` and ``ntot`` summarise what was seen, and
    ``obs`` optionally pins the latent belief at rounds where a private answer
    happens to be recorded. Everything is (n_seq, T+1).
    """

    x: np.ndarray
    n1: np.ndarray
    ntot: np.ndarray
    mask: np.ndarray
    obs: np.ndarray          # -1 unknown, else the observed belief bit

    @property
    def n_seq(self):
        return self.x.shape[0]

    @property
    def rounds(self):
        return self.x.shape[1] - 1


def sequences(t: Transcript, condition: str, private_rounds=(0,),
              baseline_branch: str = "r0") -> Sequences:
    """Transcript -> padded arrays. ``private_rounds`` says where PRIVATE is kept.

    ``(0,)`` is the ordinary-log case: the pre-interaction answer is public
    anyway, so nothing is being assumed that a normal transcript lacks. ``()``
    hides even that. ``(0, T)`` is the terminal-probe design. Passing every round
    reproduces the fully observed case and is useful only as an upper bound.
    """
    truth = t.truth()
    by = {(r["task_id"], r["agent"], r["round"], r["branch"]): r for r in t.rows}
    T = t.rounds
    keep = set(private_rounds)
    rows = []
    for task in sorted({r["task_id"] for r in t.rows}):
        tr = truth.get(task)
        if tr is None:
            continue
        for ag in sorted({r["agent"] for r in t.rows}):
            r0 = by.get((task, ag, 0, baseline_branch))
            if r0 is None or not r0.get("public"):
                continue
            xs = [int(r0["public"] == tr)]
            n1s, nts, ms = [0], [0], [False]
            obs = [int(r0["private"] == tr) if (0 in keep and r0.get("private"))
                   else -1]
            ok = True
            for rnd in range(1, T + 1):
                row = by.get((task, ag, rnd, condition))
                if row is None or not row.get("public") or not row.get("nb_public"):
                    ok = False
                    break
                seen = [int(v == tr) for v in row["nb_public"] if v]
                if not seen:
                    ok = False
                    break
                xs.append(int(row["public"] == tr))
                n1s.append(int(sum(seen)))
                nts.append(len(seen))
                ms.append(True)
                obs.append(int(row["private"] == tr)
                           if (rnd in keep and row.get("private")) else -1)
            if ok and len(xs) > 1:
                rows.append((xs, n1s, nts, ms, obs))
    if not rows:
        return Sequences(*[np.zeros((0, T + 1)) for _ in range(4)],
                         obs=np.zeros((0, T + 1)))
    return Sequences(
        x=np.array([r[0] for r in rows], dtype=np.int8),
        n1=np.array([r[1] for r in rows], dtype=np.int16),
        ntot=np.array([r[2] for r in rows], dtype=np.int16),
        mask=np.array([r[3] for r in rows], dtype=bool),
        obs=np.array([r[4] for r in rows], dtype=np.int8))


def loglik(S: Sequences, c: float, a: float, rho: float, r: float,
           eps: float = 0.02) -> float:
    """Exact log-likelihood of the expressions, beliefs marginalised out.

    Vectorised over sequences; the only Python loop is over rounds, of which
    there are three. A fit is milliseconds, so profile intervals come for free.
    """
    if S.n_seq == 0:
        return -np.inf
    # alpha[s, b] = P(expressions up to t, belief_t = b)
    alpha = np.zeros((S.n_seq, 2))
    x0 = S.x[:, 0].astype(int)
    alpha[np.arange(S.n_seq), x0] = 1.0          # round 0: said = believed
    _pin(alpha, S.obs[:, 0])

    redraw = np.array([1.0 - r, r]) if TRUTH_BIT == 1 else np.array([r, 1.0 - r])
    for t in range(1, S.rounds + 1):
        m = S.mask[:, t]
        if not m.any():
            continue
        xt = S.x[m, t].astype(int)
        n1, nt = S.n1[m, t].astype(float), S.ntot[m, t].astype(float)
        tie = 2 * n1 == nt
        Mbit = (2 * n1 > nt).astype(int)
        nxt = np.zeros((m.sum(), 2))
        for bp in (0, 1):
            w_prev = alpha[m, bp]
            if not np.any(w_prev > 0):
                continue
            d = np.where(bp == 1, (nt - n1) / nt, n1 / nt)
            eng = np.minimum(rho * d, 1.0)
            contradicted = (~tie) & (Mbit != bp)
            said_own = xt == bp
            said_other = xt == (1 - bp)

            # concealed: only reachable when contradicted and the agent said M
            w_con = np.where(contradicted & said_other, c, 0.0)
            # disclosed, or the room already agreed: the agent said its belief
            w_dis = np.where(contradicted & said_own, 1.0 - c,
                             np.where(~contradicted & said_own, 1.0, 0.0))

            J = np.zeros((m.sum(), 2))
            other = 1 - bp
            J[:, other] += w_con * a
            J[:, bp] += w_con * (1.0 - a)
            for b in (0, 1):
                post = eng * redraw[b] + (1.0 - eng) * (1.0 if b == bp else 0.0)
                J[:, b] += w_dis * post
            J = (1.0 - eps) * J + eps * 0.25     # off-model round
            nxt += w_prev[:, None] * J
        alpha[m] = nxt
        alpha[~m] = alpha[~m]                     # padded rounds carry through
        _pin(alpha, S.obs[:, t])
        s = alpha.sum(axis=1, keepdims=True)
        if np.any(s <= 0):
            return -np.inf
    return float(np.log(alpha.sum(axis=1)).sum())


def _pin(alpha, obs):
    """Zero the branch a recorded private answer rules out."""
    known = obs >= 0
    if not known.any():
        return
    idx = np.flatnonzero(known)
    wrong = 1 - obs[known].astype(int)
    alpha[idx, wrong] = 0.0


GRID = np.linspace(0.02, 0.98, 49)
GRID_EPS = np.array([0.002, 0.005, 0.01, 0.02, 0.04, 0.07, 0.10, 0.15, 0.22,
                     0.30, 0.40])


def fit_latent(t: Transcript, condition: str, private_rounds=(0,), iters: int = 8,
               fit_eps: bool = True, seed_params=None) -> dict:
    """Coordinate ascent on the grid. Returns the estimates and a profile interval.

    The surface is smooth and four-dimensional, so a grid beats an optimiser: it
    cannot land in a local mode and it gives the profile likelihood for free.
    """
    S = sequences(t, condition, private_rounds=private_rounds)
    if S.n_seq == 0:
        return dict(n_seq=0)
    est = dict(seed_params or dict(c=0.5, a=0.5, rho=0.5, r=0.7, eps=0.05))
    if not fit_eps:
        est["eps"] = est.get("eps", 0.02)
    axes = [("c", GRID), ("a", GRID), ("rho", GRID), ("r", GRID)]
    if fit_eps:
        axes.append(("eps", GRID_EPS))
    profiles = {}
    for _ in range(iters):
        for k, grid in axes:
            lls = np.array([loglik(S, **{**est, k: float(v)}) for v in grid])
            est[k] = float(grid[int(np.argmax(lls))])
            profiles[k] = (grid, lls)
    out = dict(est)
    out["n_seq"] = S.n_seq
    out["loglik"] = loglik(S, **est)
    # Profile interval: the set within 1.92 log-likelihood of the maximum, the
    # usual chi-square(1) 95% cut. Approximate -- sequences within a task are not
    # independent -- so it is a lower bound on the width, and said to be.
    for k, (grid, lls) in profiles.items():
        ok = grid[lls >= lls.max() - 1.92]
        out[f"{k}_lo"], out[f"{k}_hi"] = float(ok.min()), float(ok.max())
    return out
