#!/usr/bin/env python3
"""Write config/transcripts.yaml: one entry per staged run, from its own record.

Every setting of a run -- model, endpoint, reasoning effort, token budget,
probe, intervention, topology, seed -- is taken from the run's
events.meta.json, and the instruction conditions from the branches its
transcript actually contains (a meta file is rewritten by every invocation on
the same events file, so its `conditions` field names only the last one). The
runner is chosen by benchmark, because a meta file does not record it.

Usage: python scripts/make_transcripts_config.py [data] > config/transcripts.yaml
"""
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
RUNNER = {"hidden_profile": "hidden_profile_debate", "hp_models": "hidden_profile_debate",
          "hp_repeats": "hidden_profile_debate", "hp_interventions": "hidden_profile_debate",
          "hiddenbench": "hiddenbench_debate", "medeinst": "hiddenbench_debate",
          "musique": "rag_debate", "llm": "llm_debate", "llm_variants": "llm_debate"}
ORDER = ["A0", "PS", "C0", "C1", "C2", "C3", "C4"]
KEEP = ["model", "endpoint", "provider", "reasoning_effort", "max_tokens", "max_budget",
        "timeout", "probe", "intervention", "topology", "k", "agents", "rounds",
        "temperature", "seed", "workers", "items"]


def entry(tree: Path, run: str) -> dict:
    meta = json.loads((tree / run / "events.meta.json").read_text())
    branches = set()
    with open(tree / run / "events.jsonl") as fh:
        for line in fh:
            if line.strip():
                r = json.loads(line)
                if r.get("round", 0) > 0:
                    branches.add(r.get("branch"))
    e = {k: meta[k] for k in KEEP if meta.get(k) not in (None, "")}
    if "seats" in meta and "agents" not in e:
        e["agents"] = meta["seats"]
    e.setdefault("endpoint", "openrouter")
    e.setdefault("probe", "joint")
    e["conditions"] = ",".join(c for c in ORDER if c in branches)
    e["runner"] = RUNNER[run.split("/")[0]]
    if e["endpoint"] == "local":
        e["base_url"] = "${LOCAL_BASE_URL}"
    return e


def main():
    data = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "data"
    manifest = yaml.safe_load((ROOT / "config/data_manifest.yaml").read_text())
    out = {"transcripts": {r: entry(data / "transcripts", r) for r in manifest["transcripts"]}}
    print("# Generated by scripts/make_transcripts_config.py from each run's events.meta.json.\n"
          "# One entry per run: the settings the paper's transcript was produced with.\n"
          "# `${LOCAL_BASE_URL}` is expanded from the environment at run time.")
    print(yaml.safe_dump(out, sort_keys=False, width=100))


if __name__ == "__main__":
    main()
